matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-6
        - g++-6
    env:
      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
  - os: osx
    osx_image: xcode9.4
language: c++
install:
- echo "Hi hello"
script:
- gcc helloworld.c
